[package]
name = "p1"
version = "0.1.0"
edition = "2021"

[lib]
name = "p1lib"
path = "src/lib.rs"

[[bin]]
name = "p1"
path = "src/bin.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version="4", features=["derive"]}
